frontend/.prettierrc
frontend/.vscode/settings.json
frontend/eslint.config.mjs
frontend/main.tsx
frontend/package-lock.json
frontend/package.json

#11 
한 줄 요약 : 팀 코드 컨벤션에 맞게 eslint와 prettier를 설정함.
- 아래와 같이 정상적으로 적용되는지 확인해주세요
감사합니다 :)

[FE] chore: eslint, pritter 환경설정

---

frontend/src/shared/components/input/Input.tsx
frontend/src/shared/components/input/input.stories.ts
frontend/src/shared/components/input/input.styled.ts
frontend/src/shared/components/textarea/Textarea.tsx
frontend/src/shared/components/textarea/textarea.stories.ts
frontend/src/shared/components/textarea/textarea.styled.ts

#21 
한 줄 요약 : 공통 컴포넌트에서 InputPage에 들어가는 input, textarea 컴포넌트를 만들었습니다.
- 공통 컴포넌트가 잘 생성되었는지 확인해주세요.
- 해당 코드는 페어프로그래밍으로 @kaori-killer 와 함께 진행하였습니다.

[FE] feat: 공통 컴포넌트 개발 - Component - InputPage (Input)

---

.github/labeler.yml
.github/workflows/labeler.yml
frontend/.storybook/preview.ts
frontend/src/shared/components/mapButton/MapButton.tsx
frontend/src/shared/components/mapButton/mapButton.stories.ts
frontend/src/shared/components/mapButton/mapButton.styled.ts
frontend/src/shared/components/mapPoint/MapPoint.tsx
frontend/src/shared/components/mapPoint/mapPoint.stories.ts
frontend/src/shared/components/mapPoint/mapPoint.styled.ts
frontend/src/shared/components/markerIndex/MarkerIndex.tsx
frontend/src/shared/components/markerIndex/markerIndex.stories.tsx
frontend/src/shared/components/markerIndex/markerIndex.styled.ts

#20, #26
한 줄 요약 : Component - ResultPage (Map, Map-Marker)에 대한 공통 컴포넌트를 개발합니다.
- 로컬에서 해당 공통 컴포넌트가 피그마 디자인에 맞게 개발되었는지 확인해주세요.
- 페어프로그래밍으로 @kaori-killer 와 함께 진행했습니다.
- 감사합니당 :]

 [FE] feat: 공통 컴포넌트 개발 - Component - ResultPage (Map, Map-Marker)

---

frontend/.storybook/preview.ts
frontend/src/shared/components/badge/Badge.tsx
frontend/src/shared/components/badge/badge.styled.ts
frontend/src/shared/components/bottomButton/BottomButton.tsx
frontend/src/shared/components/bottomButton/bottomButton.styled.ts
frontend/src/shared/components/mapButton/MapButton.tsx
frontend/src/shared/components/mapButton/mapButton.styled.ts
frontend/src/shared/components/mapPoint/MapPoint.tsx
frontend/src/shared/components/mapPoint/mapPoint.styled.ts
frontend/src/shared/components/markerIndex/MarkerIndex.tsx
frontend/src/shared/components/markerIndex/markerIndex.styled.ts
frontend/src/shared/components/spotItem/SpotItem.tsx
frontend/src/shared/components/spotItem/spotItem.stories.ts
frontend/src/shared/components/spotItem/spotItem.styled.ts
frontend/src/shared/components/tag/Tag.tsx
frontend/src/shared/components/tag/tag.styled.ts
frontend/src/shared/styles/default.styled.ts

resolve #24 
한 줄 요약 : 공통 컴포넌트(SpotItem) 개발
- 로컬에서 잘 동작하는지 확인해주세요.
- @eunsoA 와 함께 페어프로그래밍으로 진행했습니다.
- 감사합니다.

[FE] feat: 공통 컴포넌트 개발 - Component - ResultPage (List)

---

.github/workflows/be-cicd-dev.yml

#51 
한 줄 요약 : 백엔드 CI/CD 스크립트를 작성했습니다.
- 스크립트 내 오타가 없는가?
- dev 브랜치에 merge된 후에 다른 브랜치에도 해당 스크립트가 workflows 디렉토리에 있어야 GitHub Actions가 동작합니다.

[BE] chore: CI/CD를 위한 GitHub Actions workflow 작업

---

frontend/main.tsx
frontend/src/app/App.tsx
frontend/src/shared/components/layout/Layout.tsx
frontend/src/shared/components/layout/layout.styled.ts

#45 
한 줄 요약 : 모든 페이지에서 범용적으로 사용되는 Layout 컴포넌트 개발 후 적용했습니다.
- 로컬에서 잘 동작하는지 확인해주세요.
- @kaori-killer 와 페어프로그래밍으로 진행했습니다.
- 감사합니다.

[FE] feat: 페이지 레이아웃 설정

---

frontend/main.tsx
frontend/package-lock.json
frontend/package.json
frontend/src/app/App.tsx
frontend/src/pages/indexPage/IndexPage.tsx
frontend/src/pages/resultPage/ResultPage.tsx
frontend/webpack.config.js

#46 
한 줄 요약 : 라우팅 설정하고 각 페이지를 연동했습니다.
- 로컬에서 라우팅이 잘 동작하는지 확인해주세요.
- @kaori-killer 와 함께 페어프로그래밍으로 진행했습니다.
- 감사합니다.

[FE] feat: 라우팅 설정

---

.github/workflows/be-cicd-dev.yml

#57 
한 줄 요약 : CI/CD workflow 스크립트 내용을 수정했습니다.
- 오타 확인

[BE] chore: CI/CD workflow 스크립트 추가 수정

---

.github/workflows/be-cicd-dev.yml

#57 
한 줄 요약 : 백엔드 개발 환경 배포가 원활하게 이루어지도록 CI/CD workflow 스크립트를 수정했습니다.
- 오타가 없는지

[BE] chore: CI/CD workflow 스크립트 내 path 수정

---

backend/src/main/java/com/f12/moitz/application/LocationService.java
backend/src/main/java/com/f12/moitz/application/dto/LocationRecommendResponse.java
backend/src/main/java/com/f12/moitz/infrastructure/gemini/GoogleGeminiClient.java

#74 
한 줄 요약 : 간헐적으로 출발지와 동일한 장소를 추천해주는 버그 수정

[BE] fix: 간헐적으로 출발지와 동일한 장소를 추천해주는 버그 수정

---

backend/src/main/java/com/f12/moitz/application/dto/LocationRecommendRequest.java

한 줄 요약 : requirement 필드 필수 제약 조건에서 선택으로 변경

feat: 필수 필드 제약 조건 제거

---

frontend/index.html

close #127 
한 줄 요약 : 웹사이트 파비콘과 타이틀을 설정했어요
- 로컬에서 잘 동작하는지 확인해주세요

[FE] feat: 웹사이트 파비콘 및 타이틀 설정

---

frontend/src/shared/components/layout/layout.styled.ts

#105 
한 줄 요약 : 모바일 환경을 고려한 레이아웃 반응형 처리
문제상황
- 모바일 환경(400px 미만)에서 레이아웃이 화면 전체를 활용하지 못하는 문제
결과
- 모바일 환경: 화면 전체를 활용하는 반응형 레이아웃 구현
- 데스크탑 환경: flex 속성을 활용하여 content 영역을 400px로 고정
- 컨텐츠 길이에 따라 자연스럽게 확장되도록 min-height 속성 적용

[FE] style: 반응형 레이아웃 수정

---

frontend/src/features/map/components/map/Map.tsx
frontend/src/features/map/hooks/useCustomOverlays.tsx
frontend/src/features/map/lib/CustomOverlay.ts
frontend/src/mocks/LocationsMock.ts
frontend/src/pages/resultPage/ResultPage.tsx
frontend/src/shared/components/markerIndex/MarkerIndex.tsx
frontend/src/shared/components/markerIndex/markerIndex.stories.tsx
frontend/src/shared/components/markerIndex/markerIndex.styled.ts
frontend/src/shared/components/spotItem/SpotItem.tsx
frontend/src/shared/styles/default.styled.ts
frontend/src/shared/styles/tokens.css
frontend/src/shared/styles/tokens.ts
frontend/src/types/global.d.ts

[FE] feat: [map] 출발지와 만날 지역리스트를 핀으로 띄운다

---

frontend/main.tsx
frontend/src/entities/contexts/LocationsContext.tsx
frontend/src/entities/contexts/LocationsProvider.tsx
frontend/src/entities/contexts/useLocationsContext.ts
frontend/src/entities/hooks/useLocations.test.tsx
frontend/src/entities/hooks/useLocations.ts
frontend/src/features/map/components/map/Map.tsx
frontend/src/features/map/hooks/useCustomOverlays.tsx
frontend/src/features/map/lib/CustomOverlay.ts
frontend/src/features/meeting/components/meetingForm/MeetingForm.tsx
frontend/src/features/meeting/hooks/useFormInfo.ts
frontend/src/mocks/LocationsMock.ts
frontend/src/pages/resultPage/ResultPage.tsx
frontend/src/shared/components/markerIndex/MarkerIndex.tsx
frontend/src/shared/components/markerIndex/markerIndex.stories.tsx
frontend/src/shared/components/markerIndex/markerIndex.styled.ts
frontend/src/shared/components/spotItem/SpotItem.tsx
frontend/src/shared/styles/default.styled.ts
frontend/src/shared/styles/tokens.css
frontend/src/shared/styles/tokens.ts
frontend/src/types/global.d.ts

[FE] feat: [IndexPage] Context API를 이용하여 상태 관리

---

frontend/src/features/meeting/components/departureInput/DepartureInput.tsx
frontend/src/features/meeting/components/departureInput/departureInput.styled.ts
frontend/src/features/meeting/components/dropdown/Dropdown.tsx
frontend/src/features/meeting/components/dropdown/dropdown.styled.ts
frontend/src/features/meeting/components/dropdown/dropdownEmpty/DropdownEmpty.tsx
frontend/src/features/meeting/components/dropdown/dropdownEmpty/dropdownEmpty.styled.ts
frontend/src/features/meeting/components/dropdown/dropdownList/DropdownList.tsx
frontend/src/features/meeting/components/dropdown/dropdownList/dropdownList.styled.ts

#161 
한 줄 요약 : indexPage 출발지 입력 시 드롭 다운을 구현했어요.
- 드롭다운을 컴포넌트로 분리할까 고민했지만, 과한 분리라는 생각이들어 `DepartureInput` 내부에 넣었습니다.

[FE] feat: indexPage 출발지 입력시 드롭다운 구현

---

.github/workflows/fe-ci.yml

#180
한 줄 요약 : CI에 테스트 및 커버리지 확인 추가
- CI가 실행될 때 test 구문도 잘 확인되나요?
-
-
-

[FE] chore: CI에 테스트 및 커버리지 확인 추가

---

frontend/src/features/meeting/components/meetingForm/MeetingForm.tsx

#189 
한 줄 요약 : indexPage 버튼 텍스트를 '모임 지역 찾기'로 수정했어요.
- 버튼 텍스트가 적절한지 체크해주세요.
-
-

[FE] feat: indexPage 버튼 텍스트 수정

---

backend/src/main/java/com/f12/moitz/application/RecommendationService.java
backend/src/main/java/com/f12/moitz/application/dto/RecommendationCreateResponse.java
backend/src/main/java/com/f12/moitz/application/dto/RecommendationsResponse.java
backend/src/main/java/com/f12/moitz/application/dto/temp/MockRecommendationResponse.java
backend/src/main/java/com/f12/moitz/application/dto/temp/RecommendationsResponse.java
backend/src/main/java/com/f12/moitz/ui/LocationController.java
backend/src/main/java/com/f12/moitz/ui/MockingRecommendationController.java
backend/src/main/java/com/f12/moitz/ui/RecommendationController.java
backend/src/main/java/com/f12/moitz/ui/SwaggerLocationController.java
backend/src/main/java/com/f12/moitz/ui/SwaggerMockingRecommendationController.java
backend/src/main/java/com/f12/moitz/ui/SwaggerRecommendationController.java
backend/src/test/java/com/f12/moitz/application/RecommendationServiceTest.java

#266 
한 줄 요약 : 변경된 API와 기존 API 로직 유지하도록 수정

[BE] fix: 기존 API 유지하도록 반영

---

.github/workflows/fe-ci.yml
.github/workflows/fe-dev-cd.yml
.github/workflows/fe-prod-cd.yml

[FE] chore: CI/CD 워크플로우에서 아티팩트 이름을 동적으로 설정하도록 수정

---

.github/workflows/fe-ci.yml
.github/workflows/fe-dev-cd.yml
.github/workflows/fe-prod-cd.yml

chore: CI/CD 워크플로우에서 아티팩트 이름 참조 방식 수정

---

.github/workflows/be-cicd-prod.yml

[BE] chore: 운영 서버 CI/CD 들여쓰기 수정

---

.github/workflows/be-cicd-prod-auto-trigger.yml

한 줄 요약 : 운영 서버 CI/CD 자동/수동 파일 분리

[BE] chore: 운영 서버 CI/CD 자동/수동 파일 분리

---

backend/src/main/java/com/f12/moitz/MoitzApplication.java
backend/src/main/java/com/f12/moitz/domain/Result.java
backend/src/main/resources/application.properties

#308 
한 줄 요약 : 7일 지난 후 결과 데이터 만료되도록 TTL 적용
- 정책 추가로 논의하여 기간 조정 가능합니다!

[BE] feat: 결과 데이터 일정 기간 저장 후 만료 기능 추가
